[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:gherkin.*
markers =
    oracle-api: ApiOracle 활성화
    oracle-console: ConsoleOracle 활성화
    oracle-network: NetworkOracle 활성화
